services:

  db:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:5000

  server:
    image: php:7
    command: -S 0.0.0.0:80 /app/index.php
    container_name: php_server
    environment:
      RENT_DURATION_IN_DAYS: ${RENT_DURATION_IN_DAYS}
      RENT_BASE_PRICE: ${RENT_BASE_PRICE}
      RENT_PER_DAY: ${RENT_PER_DAY}
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - db

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app

  composer_updater:
    restart: 'no'
    image: composer
    command: update
    volumes:
      - .:/app