services:

  db:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build:
      context: ./docker/php
      args:
        php_version: 7.3-apache
    container_name: php_server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db